# .gitlab-ci.yml

image: node:lts-bookworm-slim

stages:
  - test
  - monitor
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."
  allow_failure: true

# accessibility:
#   stage: monitor
lighthouse:
  stage: monitor
  image: node:lts-bookworm-slim
  script:
    - apt-get update && apt-get install -y nodejs npm chromium
    - export CHROME_BIN=chromium
    - npm install -g lighthouse
    - groupadd -r lighthouse && useradd -r -g lighthouse lighthouse
    - chown -R lighthouse:lighthouse /usr/bin/chromium
    - sudo -u lighthouse lighthouse https://rosiethebatdog.netlify.app --output json --output-path=./lighthouse-report.json --no-sandbox
  allow_failure: true

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
