# .gitlab-ci.yml

image: node:lts-bookworm-slim
# turning off test and deploy to save resources
stages:
  # - test
  - monitor
  # - deploy

# unit_test:
#   stage: test
#   script:
#     - echo "Running unit tests..."
#     - npm install
#     - npm run test
#   allow_failure: true

# e2e:
#   stage: test
#   script:
#     - echo "Running e2e tests..."
#   allow_failure: true

# integration:
#   stage: test
#   script:
#     - echo "Running integration tests..."
#   allow_failure: true

accessibility:
  stage: monitor
  script:
    - echo "Running accessibility test..."
    - echo "a11y_urls: $a11y_urls"  # Print the value of a11y_urls variable
  variables:
    a11y_urls: "https://about.gitlab.com https://rosiethebatdog.netlify.app"
  # include:
  #   - template: "./Accessibility.gitlab-ci.yml"
  image: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/ci-cd/accessibility:6.2.3"
  script:
    - /gitlab-accessibility.sh "$a11y_urls"
  allow_failure: true
  artifacts:
    when: always
    expose_as: 'Accessibility Reports'
    paths: ['reports/']
    reports:
      accessibility: reports/gl-accessibility.json
  artifacts:
    name: accessibility_reports_${CI_COMMIT_SHORT_SHA}_${CI_COMMIT_REF_SLUG}_$(date +%Y%m%d-%H%M%S).zip
  rules:
    - if: $a11y_urls

lighthouse:
  stage: monitor
  image: node:lts-bookworm-slim
  script:
    - apt-get update && apt-get install -y nodejs npm chromium
    - export CHROME_BIN=chromium
    - npm install -g lighthouse
    - groupadd -r lighthouse && useradd -r -g lighthouse lighthouse
    - chown -R lighthouse:lighthouse /usr/bin/chromium
    - su - lighthouse -c "lighthouse https://rosiethebatdog.netlify.app --output json --output-path=./lighthouse-report.json --no-sandbox"
  allow_failure: true

# deploy:
#   stage: deploy
#   script:
#     - echo "Deploying to production..."
