# .gitlab-ci.yml

image: node:lts-bookworm-slim

stages:
  - test
  - monitor
  - deploy

unit_test:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm install
    - npm run test
  allow_failure: true

e2e:
  stage: test
  script:
    - echo "Running e2e tests..."
  allow_failure: true

integration:
  stage: test
  script:
    - echo "Running integration tests..."
  allow_failure: true

stages:
  - monitor
  variables:
    a11y_urls: "https://about.gitlab.com https://gitlab.com/users/sign_in"
  include:
    - template: "Verify/Accessibility.gitlab-ci.yml"
  allow_failure: true

lighthouse:
  stage: monitor
  image: node:lts-bookworm-slim
  script:
    - apt-get update && apt-get install -y nodejs npm chromium
    - export CHROME_BIN=chromium
    - npm install -g lighthouse
    - groupadd -r lighthouse && useradd -r -g lighthouse lighthouse
    - chown -R lighthouse:lighthouse /usr/bin/chromium
    - su - lighthouse -c "lighthouse https://rosiethebatdog.netlify.app --output json --output-path=./lighthouse-report.json --no-sandbox"
  allow_failure: true

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
