# .gitlab-ci.yml

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."
  allow_failure: true

lighthouse:
  stage: test
  script:
    - apt-get update && apt-get install -y nodejs npm
    - export CHROME_PATH=/path/to/chrome_or_chromium_executable
    - npm install -g lighthouse
    - lighthouse https://rosiethebatdog.netlify.app --output json --output-path=./lighthouse-report.json
  allow_failure: true

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
