# .gitlab-ci.yml
# templates
# https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/ci/templates/Jobs

image: node:lts-bookworm-slim
# turning off test and deploy to save resources
stages:
  - test
  - monitor
  - performance_test
  # - deploy

unit_test:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm install
    - npm run test
  allow_failure: true
  rules:
    - when: manual

e2e:
  stage: test
  script:
    - echo "Running e2e tests..."
  allow_failure: true
  rules:
    - when: manual

integration:
  stage: test
  script:
    - echo "Running integration tests..."
  allow_failure: true
  rules:
    - when: manual

k6-loadtest-local:
  stage: performance_test
  image: 
    name: grafana/k6:latest
    entrypoint: [""]
  script:
    - k6 run ./scripts/performance-test.js

k6-loadtest-cloud:
  stage: performance_test
  image: 
    name: grafana/k6:latest
    entrypoint: [""]
  script:
    - k6 cloud ./scripts/performance-test.js
  rules:
    - when: manual