# .gitlab-ci.yml

image: node:lts-bookworm-slim

stages:
  - test
  - monitoring
  - deploy

test:
  stage: test
  script:
    - echo "Running tests..."
  allow_failure: true

accessibility:
  stage: monitoring

lighthouse:
  stage: monitoring
  script:
    - apt-get update && apt-get install -y nodejs npm 
    - apt-get install -y google-chrome
    - export CHROME_PATH=/usr/bin/google-chrome
    - npm install -g lighthouse
    - lighthouse https://rosiethebatdog.netlify.app --output json --output-path=./lighthouse-report.json
  allow_failure: true

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
